version: '3.1'

services:

  mysql-employee:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
      
  employee-service:
    image: employee-service
    build: ./
    ports:
    - 8080:8080
    depends_on:
      - mysql-employee